version: '2'

services:
    router:
        restart: always
        build: ./router
        privileged: true
        network_mode: "host"

    broker:
        restart: always
        build: ./broker
        network_mode: "host"
        environment:
            BACKEND: http://127.0.0.1
        ports:
            - 5683:5683/udp
        depends_on:
            - router
